name: Clarity
favicon: null
layout_spectrum: 0.3931609350256622
typography_spectrum: 0.37504102010279894
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.04227647138759494
  lightness: 0.446647648466751
  saturation: 0.46477621141821146
  rhythmicContrast: 0.8202633715700358
purpose: []
